# Generated by Django 4.2.3 on 2023-07-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('descripcion_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=40)),
                ('numero_telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad_stock', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.categoria')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha_factura', models.DateField()),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detfac', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.producto')),
            ],
        ),
    ]
